---
name: GHCR Release
on:
  workflow_dispatch:
  # release:
  #   types:
  #     - created
  # push:
  #   tags:
  #     - v*

jobs:
    publish-ghcr:
        permissions:
            contents: write
            issues: write
            pull-requests: write
        runs-on: ubuntu-latest
        strategy:
          matrix:
            platforms: [linux/amd64, linux/arm64]
        steps:
          -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v3
          -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
          - 
            name: Log in to the Container registry
            uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
            with:
              registry: https://ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
          - 
            name: Build and push Docker image
            uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
            with:
              context: .
              file: ./Dockerfile
              platforms: ${{ matrix.platforms }}
              push: true
              outputs: type=image,name=swimgenerator,annotation-index.org.opencontainers.image.description=Swim Generator multi-arch image
