name: Release
on:
  push:
    branches:
      - main

jobs:
    release:
        permissions:
            contents: write
            issues: write
            pull-requests: write
        runs-on: ubuntu-latest
        strategy:
          matrix:
            platforms: [linux/amd64, linux/arm64]
        steps:
            - 
              uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
            - 
              name: Set up Node.js
              uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
              with:
                node-version: '20.8.1'
            - run: npx semantic-release
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            -
              name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            -
              name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - 
              name: Log in to the Container registry
              uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
              with:
                registry: https://ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - 
              name: Build and push Docker image
              uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
              with:
                context: .
                file: ./Dockerfile
                platforms: ${{ matrix.platforms }}
                push: true
                outputs: type=image,name=swimgenerator,annotation-index.org.opencontainers.image.description=Swim Generator multi-arch image
                