#code from https://semantic-release.gitbook.io/semantic-release/recipes/ci-configurations/github-actions

name: Release
on:
  push:
    branches:
      - main # or main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@6d193bf28034eafb982f37bd894289fe649468fc #v4.1.7
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@97ca147735c170fb35096b39ef17a0fc5d9270ac #v4.0.3
        with:
          node-version: "20.8.1"
      - name: Install dependencies
        run: npm clean-install
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
